name: Docker CI for new releases

on:
  release:
    types: [published]

jobs:
  build_and_push_to_registry:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v3
      -
        name: Get release version
        run: echo "TAG=$(echo "$GITHUB_REF" | awk -F '/' '{print $3}')" >> $GITHUB_ENV
      -  
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/uawa:${{ env.TAG }}
          build-args: |
              BRANCH=${{ env.TAG }}