name: Python unittest

on:
  pull_request:
    types: [opened, reopened]

jobs:
  test_code:
    name: Test Python code with unittest
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v3
      - 
        name: Set up Python
        uses: actions/setup-python@v2
      - 
        name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - 
        name: Test with unittest
        run: |
          python3 -m unittest